import {
  // 일반·UI
  ShoppingCart, Flower2, Brush, ChefHat, Rocket, Package, Save, Download, Upload,
  FileText, BarChart3, Shield, RotateCw, GraduationCap, ClipboardList, Smartphone,
  Sparkles, Flame, Moon, Wand2, Stethoscope, Brain, Coffee, CloudSun, Sun, Sunrise,
  Snowflake, Leaf, Cloud, CloudRain, CloudFog, Lightbulb, Bell, Zap,
  // 식품
  Apple, Beef, Fish, Milk, GlassWater, Cookie, CookingPot, UtensilsCrossed, Croissant,
  Pill, Soup, Salad, Cake,
  // 패션
  Shirt, Footprints, ShoppingBag, Glasses, Watch, Gem, Crown,
  // 사람·관계
  User, Users, Heart, HeartHandshake,
  // 동작·상태
  AlertTriangle, Check, X, Trophy, Timer, Search, Plus, Minus, Trash2, Edit3,
  Settings, Camera, Image as ImageIcon, Calendar, MapPin, Link as LinkIcon,
  ThumbsUp, MessageCircle, Bookmark, Star, Map, Refrigerator, Pencil,
  Sprout, Mail, Phone, Tag, Activity, BookOpen, ChefHat as ChefHatIcon,
  type LucideIcon,
} from 'lucide-react';

/**
 * 이모지 → Lucide 라인 아이콘 매핑.
 * 사용처에서 `<span>{emoji}</span>` 대신 `<EmojiIcon emoji="🛒" />` 로.
 */
export const EMOJI_TO_ICON: Record<string, LucideIcon> = {
  // ─── 일반 UI ───
  '🛒':  ShoppingCart,
  '🛍️': ShoppingBag,
  '🌸':  Flower2,
  '🌱':  Sprout,
  '🌿':  Leaf,
  '🌳':  Sprout,
  '🧹':  Brush,
  '🍳':  ChefHatIcon,
  '🚀':  Rocket,
  '📦':  Package,
  '💾':  Save,
  '📥':  Download,
  '📤':  Upload,
  '📄':  FileText,
  '📃':  FileText,
  '📑':  FileText,
  '📊':  BarChart3,
  '📈':  Activity,
  '📉':  Activity,
  '🛡':  Shield,
  '🛡️': Shield,
  '🔄':  RotateCw,
  '🎓':  GraduationCap,
  '📋':  ClipboardList,
  '📱':  Smartphone,
  '✨':  Sparkles,
  '⭐':  Star,
  '🔥':  Flame,
  '🆕':  Sparkles,
  '🆗':  Check,
  '🌙':  Moon,
  '🪄':  Wand2,
  '🩺':  Stethoscope,
  '🧠':  Brain,
  '💡':  Lightbulb,
  '🔔':  Bell,
  '⚡':  Zap,
  '📅':  Calendar,
  '🗓️': Calendar,
  '📍':  MapPin,
  '🔗':  LinkIcon,
  '👍':  ThumbsUp,
  '💬':  MessageCircle,
  '📷':  Camera,
  '🖼':  ImageIcon,
  '🖼️': ImageIcon,
  '✏️':  Pencil,
  '✏':   Pencil,
  '📝':  Edit3,
  '⚙️':  Settings,
  '⚙':   Settings,
  '🏷️':  Tag,
  '🏷':   Tag,
  '📖':  BookOpen,
  '📚':  BookOpen,
  '🗺️': Map,
  '🗺':   Map,
  '✉️':  Mail,
  '✉':   Mail,
  '📧':  Mail,
  '📞':  Phone,
  '📲':  Smartphone,

  // ─── 시간대 / 날씨 ───
  '☀️':  Sun,
  '☀':   Sun,
  '🌅':  Sunrise,
  '🌄':  Sunrise,
  '🌤':  CloudSun,
  '🌤️': CloudSun,
  '🌥':  Cloud,
  '🌥️': Cloud,
  '☁':   Cloud,
  '☁️':  Cloud,
  '🌧':  CloudRain,
  '🌧️': CloudRain,
  '❄️':  Snowflake,
  '❄':   Snowflake,
  '🌫':  CloudFog,
  '🌫️': CloudFog,
  '🌆':  CloudSun,

  // ─── 식품 ───
  '🥬':  Apple,
  '🥕':  Apple,
  '🍎':  Apple,
  '🍓':  Apple,
  '🍇':  Apple,
  '🍊':  Apple,
  '🍐':  Apple,
  '🍑':  Apple,
  '🍒':  Apple,
  '🍅':  Apple,
  '🍆':  Apple,
  '🥒':  Apple,
  '🌽':  Apple,
  '🥑':  Apple,
  '🍌':  Apple,
  '🥩':  Beef,
  '🍖':  Beef,
  '🥚':  Beef,
  '🐟':  Fish,
  '🦐':  Fish,
  '🦑':  Fish,
  '🦪':  Fish,
  '🥛':  Milk,
  '🧀':  Milk,
  '🧃':  GlassWater,
  '🍶':  GlassWater,
  '🍵':  GlassWater,
  '🍪':  Cookie,
  '🍫':  Cookie,
  '🍬':  Cookie,
  '🍰':  Cake,
  '🧁':  Cake,
  '🥧':  Cake,
  '🧂':  CookingPot,
  '🍜':  UtensilsCrossed,
  '🍱':  UtensilsCrossed,
  '🍙':  UtensilsCrossed,
  '🍚':  UtensilsCrossed,
  '🍛':  UtensilsCrossed,
  '🍝':  UtensilsCrossed,
  '🍞':  Croissant,
  '🥐':  Croissant,
  '🥖':  Croissant,
  '💊':  Pill,
  '🍲':  Soup,
  '🍵 ': Soup,
  '🥗':  Salad,
  '🥘':  CookingPot,
  '🥪':  UtensilsCrossed,
  '☕':  Coffee,

  // ─── 패션 ───
  '👕':  Shirt,
  '👖':  Shirt,
  '🧥':  Shirt,
  '👗':  Shirt,
  '👚':  Shirt,
  '🥻':  Shirt,
  '👟':  Footprints,
  '👠':  Footprints,
  '👞':  Footprints,
  '🥾':  Footprints,
  '👜':  ShoppingBag,
  '👝':  ShoppingBag,
  '🎒':  ShoppingBag,
  '🧢':  Shirt,
  '🧣':  Shirt,
  '🧤':  Shirt,
  '🧦':  Shirt,
  '👓':  Glasses,
  '🕶️':  Glasses,
  '🕶':   Glasses,
  '⌚':  Watch,
  '💍':  Gem,
  '👑':  Crown,
  '💄':  Sparkles,

  // ─── 사람 / 관계 ───
  '👤':  User,
  '👥':  Users,
  '🧒':  User,
  '👶':  User,
  '🧑':  User,
  '👩':  User,
  '👨':  User,
  '🧓':  User,
  '🧑‍🦳': User,
  '👨‍🦰': User,
  '👩‍🦰': User,
  '💞':  Heart,
  '💕':  Heart,
  '💖':  Heart,
  '❤️':  Heart,
  '❤':   Heart,
  '♥':   Heart,
  '♡':   Heart,
  '🤝':  HeartHandshake,

  // ─── 동작 / 상태 ───
  '⚠':   AlertTriangle,
  '⚠️':  AlertTriangle,
  '✓':   Check,
  '✔':   Check,
  '✔️':  Check,
  '×':   X,
  '✕':   X,
  '✖':   X,
  '✖️':  X,
  '🏆':  Trophy,
  '⏱':  Timer,
  '⏱️': Timer,
  '⏰':  Timer,
  '🔍':  Search,
  '🔎':  Search,
  '+':   Plus,
  '–':   Minus,
  '🗑':  Trash2,
  '🗑️': Trash2,

  // ─── 가전·기타 ───
  '🧊':  Refrigerator,
  '🍻':  GlassWater,
  '🎯':  Bookmark,
  '🎨':  Sparkles,
  '🍂':  Leaf,
  '🐶':  Sprout,
  '🐱':  Sprout,
  '🦁':  Sprout,
  '🍯':  CookingPot,
  '🥦':  Apple,
  '🐙':  Fish,
  '🦪 ': Fish,
};

interface EmojiIconProps {
  emoji:        string;
  size?:        number;
  strokeWidth?: number;
  className?:   string;
  /** 매핑 없을 때 폴백: 'emoji' (이모지 그대로) | 'hide' (숨김) */
  fallback?:    'emoji' | 'hide';
}

/**
 * 이모지를 Lucide 라인 아이콘으로 렌더.
 * 매핑 없으면 폴백 옵션에 따라 원래 이모지 표시 또는 숨김.
 */
export default function EmojiIcon({
  emoji,
  size        = 16,
  strokeWidth = 2,
  className   = '',
  fallback    = 'emoji',
}: EmojiIconProps) {
  const Icon = EMOJI_TO_ICON[emoji];
  if (!Icon) {
    if (fallback === 'hide') return null;
    return <span className={className} aria-hidden>{emoji}</span>;
  }
  return <Icon size={size} strokeWidth={strokeWidth} className={className} aria-hidden />;
}
